### ISSUE TITLE
Cascade several 7-segment display modules

### ISSUE THREAD

**Issue by bschymanski** [adafruit/Adafruit_CircuitPython_MAX7219#39]
is it possible to use (cascade) multiple max7219 7-segment display modules?

**Comment by tekktrik** [comment]
Datasheet says it's doable!  Check out page 13:

https://cdn-shop.adafruit.com/datasheets/MAX7219.pdf

**Comment by bschymanski** [comment]
Yes, but the library does not allow to set more then 8 digits.

**Comment by tekktrik** [comment]
Ah, got it!   I wonder if it can be made configurable!

**Comment by bschymanski** [comment]
Hi,

how should i use the code now?
This does not work: "segment = bcddigits.BCDDigits(spi, cs, nDigits=16)"

code.py output:
Traceback (most recent call last):
  File "code.py", line 14, in <module>
  File "adafruit_max7219/bcddigits.py", line 41, in __init__
  File "adafruit_max7219/max7219.py", line 101, in __init__
  File "adafruit_max7219/bcddigits.py", line 52, in init_display
  File "adafruit_max7219/max7219.py", line 161, in write_cmd
OverflowError: value must fit in 1 byte(s)

**Comment by tekktrik** [comment]
@bschymanski you'll need to save this library (as specifically this pull request branch) from GitHub and place it in your board's lib folder in order to test it

**Comment by tekktrik** [comment]
You can download the repository as this ZIP file:  https://github.com/tekktrik/Adafruit_CircuitPython_MAX7219/archive/refs/heads/dev/chainable-bcd-digits.zip

Take the folder labeled `adafruit_max7219` in there and use it instead of the one you've been using.  That way we can test this in progress branch.

**Comment by tekktrik** [comment]
Once you do that, you should be able to use it as you've done earlier with:

```python
segment = bcddigits.BCDDigits(spi, cs, nDigits=16)
```

If not, I'll have to make changes!

**Comment by bschymanski** [comment]
I still get the same error:
code.py output:
Traceback (most recent call last):
  File "code.py", line 15, in <module>
  File "/lib/adafruit_max7219/bcddigits.py", line 42, in __init__
  File "/lib/adafruit_max7219/max7219.py", line 190, in __init__
  File "/lib/adafruit_max7219/max7219.py", line 101, in __init__
  File "/lib/adafruit_max7219/bcddigits.py", line 53, in init_display
  File "/lib/adafruit_max7219/max7219.py", line 207, in write_cmd
OverflowError: value must fit in 1 byte(s)

**Comment by tekktrik** [comment]
Thanks for testing!  I see the issue, I'll let you know when it's ready for another test!

**Comment by tekktrik** [comment]
Okay @bschymanski I should have fixed that error, so hopefully if you redownload the library and use it, it should be good!

https://github.com/tekktrik/Adafruit_CircuitPython_MAX7219/archive/refs/heads/dev/chainable-bcd-digits.zip

**Comment by bschymanski** [comment]
Hi,

i am so sorry, but it sill produces the same error:

code.py output:
Traceback (most recent call last):
  File "code.py", line 14, in <module>
  File "/lib/adafruit_max7219/bcddigits.py", line 42, in __init__
  File "/lib/adafruit_max7219/max7219.py", line 190, in __init__
  File "/lib/adafruit_max7219/max7219.py", line 101, in __init__
  File "/lib/adafruit_max7219/bcddigits.py", line 52, in init_display
  File "/lib/adafruit_max7219/max7219.py", line 213, in write_cmd
OverflowError: value must fit in 1 byte(s)

Code done running.


This ist the sketch running on the raspberry pi pico:

import time
import board
import busio
import digitalio

import adafruit_framebuf

from adafruit_max7219 import bcddigits

mosi = board.GP7
clk = board.GP6
cs = digitalio.DigitalInOut(board.GP5)
spi = busio.SPI(clk, MOSI=mosi)
leds = bcddigits.BCDDigits(spi, cs, nDigits=16)


leds.brightness(0)
leds.clear_all()
# place 8-digit number on display
value = 12345678

leds.show_str(0, "{:8}".format(value))
leds.show()

**Comment by tekktrik** [comment]
Thank you so, so much again for helping me test this.  It seems I forgot to use a bit mask to keep the number(s) being sent fitting within a single byte.  The latest code I pushed fixes this.  Redownloading from the link should provide the fix.

**Comment by bschymanski** [comment]
Hi, no problem, i would like to use it afterwards...

and it kind of works... at least it does not give me an error anymore, but the output is not what i would expect, it is not really daisy chained:

This is the code:

```python
import time
import board
import busio
import digitalio

import adafruit_framebuf

from adafruit_max7219 import bcddigits

mosi = board.GP7
clk = board.GP6
cs = digitalio.DigitalInOut(board.GP5)
spi = busio.SPI(clk, MOSI=mosi)
leds = bcddigits.BCDDigits(spi, cs, nDigits=16)


leds.brightness(0)
leds.clear_all()
# place 8-digit number on display
value = 12345678

leds.show_str(0, "11112222")
leds.show_str(8, "33334444")
leds.show()
```

and the output looks like this:
![IMG20220406194939](https://user-images.githubusercontent.com/34037236/162037627-334f3b07-6cdd-45dd-91f5-4bba09421003.jpg)

**Comment by tekktrik** [comment]
Progress!  Let me look into what's going on here, I'm probably not doing the SPI communication correctly.  Thanks again for testing!

**Comment by Jibun-no-Kage** [comment]
@bschymanski, Post the working code?

**Comment by SparkDustJoe** [comment]
I have a Pi Zero 2 W acting as an NTP server with dedicated GNSS and RTC, but there's no display, just the blinking of the CPU activity light and the Pulse Per Second signal from the GNSS module. I'd like to get it to display details about the current condition in a display that's readable from halfway across the room rather than relying on an LCD/OLED.

I attempted to use this library to run two MAX7219-based 7-segment displays on the same SPI bus.  There are several things that I think need flushing out.
1. Proper level shifting (Pi = 3.3V I/O, MAX chip = 5V).  If the MAX and the PI are running on the same voltage OR a proper level shifter is put in-line with the SPI signals, we might have better luck, but that doesn't address...
2. The CS line from the PI isn't toggled to a "neutral/deselected" state for a given device. So for example, if I have two LED objects, each with their own CS Pin object, what will happen is data from the second one will spill onto the first one, or the data will get messed up altogether.  HOWEVER, if I manually set the CS pin value for the non-addressed device to False, the corruption seems to get much better.  The library isn't "letting go" of the bus at the end of an operation. (I should also note, I set the Pin drive mode to PUSH_PULL, and that didn't help by itself, I still had to explicitly set the pin value)

It just seems the library isn't accounting for there being more than one device in parallel OR cascaded with individual CS pins.  Simply wiring all 5 wires from the back of the first device to the input of the second means no matter which one I address they both show the same thing.  If I run separate CS signals, I get the above behavior regardless if I run the SPI signals in parallel or in series (that is, both displays getting some of each other's data and corrupting the resulting display).

I'm going to toy around with this and see if there's a place where putting in a specific Pin control signal to "let go" of the bus when the transmission ends will help resolve my specific issue. Might make it more reliable for others as well...
