### ISSUE TITLE
font5x8.bin

### ISSUE THREAD

**Issue by DrNebin** [adafruit/Adafruit_CircuitPython_MAX7219#48]
I am getting this error.

Could not find font file font5x8.bin
Traceback (most recent call last):
  File "<stdin>", line 42, in <module>
  File "adafruit_max7219/matrices.py", line 75, in text
  File "adafruit_framebuf.py", line 507, in text
  File "adafruit_framebuf.py", line 581, in __init__
OSError: [Errno 2] No such file/directory: font5x8.bin

I have the bin file and tried placing it in the library folder on the device but still get the error. The library still has this issue and if anyone knows how to resolve it (i.e. where I am to place the bin file) please let me know.

**Comment by kylefmohr** [comment]
I used the [bin file found here](https://github.com/adafruit/Adafruit_CircuitPython_framebuf/blob/main/examples/font5x8.bin) and simply placing it in the root directory (next to code.py) did the trick for me.
